Repository HelloWorld-AICC/HelloWorld-Server-Webflux, pull requests merged in 2024-09, with the labels that each got.

#29 ci : 로드밸런싱 적용
  src/main/java/Helloworld/helloworld_webflux/web/controller/RootController.java
Labels: :sparkles: feat, cicd

#31 ci : Swagger Reverse Proxy 적용
  src/main/resources/application.yml
Labels: :sparkles: feat, cicd

#35 [Refactor/#34] 스웨거 URL 수정
  src/main/java/Helloworld/helloworld_webflux/config/SwaggerConfig.java
Labels: bug

#39 모델 주소 변경
  src/main/java/Helloworld/helloworld_webflux/service/ChatServiceImpl.java
Labels: enhancement

#41 Feat#40
  src/main/java/Helloworld/helloworld_webflux/service/SummaryServiceImpl.java
Labels: enhancement

#45 모델 url 수정
  src/main/java/Helloworld/helloworld_webflux/service/ChatServiceImpl.java
Labels: enhancement
