Repository HelloWorld-AICC/HelloWorld-Server-Webflux, pull requests merged in 2024-10, with the labels that each got.

#47 chat api 리펙토링
  src/main/java/Helloworld/helloworld_webflux/service/ChatService.java
  src/main/java/Helloworld/helloworld_webflux/service/ChatServiceImpl.java
  src/main/java/Helloworld/helloworld_webflux/web/controller/ChatController.java
Labels: enhancement

#49 Feat#48
  src/main/java/Helloworld/helloworld_webflux/service/RoomService.java
  src/main/java/Helloworld/helloworld_webflux/service/RoomServiceImpl.java
  src/main/java/Helloworld/helloworld_webflux/web/controller/ChatController.java
Labels: :sparkles: feat

#55 [refactor/#54] @Property 어노테이션 제거
  src/main/java/Helloworld/helloworld_webflux/config/auth/JwtTokenProvider.java
Labels: :recycle: refactor

#57 [feat/#56] Apply Reactive Security
  build.gradle
  src/main/java/Helloworld/helloworld_webflux/config/SecurityConfig.java
  src/main/java/Helloworld/helloworld_webflux/config/auth/CustomAuthenticationToken.java
  src/main/java/Helloworld/helloworld_webflux/config/auth/JwtTokenProvider.java
  src/main/java/Helloworld/helloworld_webflux/web/controller/UserController.java
Labels: :sparkles: feat
